name: Update README with Star Counts

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_readme.py

      - name: Check for Changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected"
            echo "## Changes Detected" >> $GITHUB_STEP_SUMMARY
          else
            echo "No changes to commit."
            echo "## No Changes to Commit" >> $GITHUB_STEP_SUMMARY
            exit 0
          
      - name: Commit and Push Changes
        if: success() && steps.check-for-changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m 'Update README with latest star counts'
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
